name, "decription + symptoms"

Tuberculosis,"Patient shows no symptoms, "
Gastroenteritis,"Patient suffers from bad stomach cramps, and frequent vomiting."
Arthritis,"Patient feels pain in joints, and is of older age."
Pneumonia,"Patient has difficulty breathing, possible inflammation in lungs."
Heart attack,"Patient feels a loss of blood supply, blockage of arteries may be the cause."
Hepatitis D,"Patient feels pain in their liver, liver feels inflamed. Patient does not have Hepatitis D vaccine."
Dengue,"Patient got stung by a mosquito and is now feeling headache, joint pain, and rashes."
Jaundice,"Patient has yellow tint to the skin, sclerae, and high blood levels in bile sample."
Alcoholic hepatitis,"Patient is a heavy alcohol user, and has been for a very long period of time. Patient goes on binge drinking sessions."
Migraine,"Patient feels severe throbbing pain and pulsing feeling on one side of their head. Also feels nauseous, vomiting, and sensitivity to light and sound. Pain is so severe it interferes with daily activities and has been ongoing for days."
Hepatitis C,"Patient suffers from inflammation of the liver. Possibly from frequent use of needle sticks."
Fungal infection,"In humans, fungal infections occur when an invading fungus takes over an area of the body and is too much for the immune system to handle. Fungi can live in the air, soil, water, and plants. There are also some fungi that live naturally in the human body. Like many microbes, there are helpful fungi and harmful fungi."
Paralysis (brain hemorrhage),"Patient feels symptoms of headache, weakness, confusion, and paralysis on one side of their body."
Typhoid,"Patient has a high fever, along with headache, constipation, chills, and muscle pain."
